import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Button } from "@/components/ui/button";
import { Play, Clapperboard } from "lucide-react";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<div className="flex">
					<h1 className="text-2xl font-bold border-b p-4 flex flex-1 items-center gap-2">
						<Clapperboard />
						Next Movie
					</h1>
				</div>
				<div className="flex">
					<div className="w-[200px] pr-4 border-r p-4 flex flex-col gap-1 shrink-0">
						<Button
							variant="outline"
							className="justify-start">
							<Play />
							All
						</Button>
						<Button
							variant="outline"
							className="justify-start">
							<Play />
							Action
						</Button>
						<Button
							variant="outline"
							className="justify-start">
							<Play />
							Drama
						</Button>
						<Button
							variant="outline"
							className="justify-start">
							<Play />
							Cartoon
						</Button>
					</div>
					<div className="p-4">{children}</div>
				</div>
			</body>
		</html>
	);
}
